model:
  vars:
    - pclass
    - sex
    - age
    - sibsp
    - parch
    - fare
    - embarked
    - name
    - boat

  vars_to_replace_category:
    - boat
  categories_to_leave:
    - "?"
  replace_with: "any"

  string_to_na: "?"
  na_type: None

  vars_to_float:
    - age
    - fare

  var_to_extract_title:
    - name
  var_name_of_title:
    - title

  vars_na_to_mean:
    - age
    - fare
  vars_na_to_mfreq:
    - embarked